---
- name: deploying new war file on flip server
  become: yes
  copy:
    src: "/opt/application/mitro/release/{{ release_name }}/{{ release_name }}_app/java/FS/dummy.war"
    dest: /opt/application/snipuser
    owner: snipuser
    group: snipuser
    mode: 0775
    remote_src: yes

- name: stop tomcat services
  become: yes
  command: service tomcat stop warn=False
  args: 
    removes: /opt/application/tomcat1

- name: start tomcat services
  become: yes
  command: service tomcat start warn=False
  args: 
    removes: /opt/application/tomcat1
    
