---
- name: deploying new war file on flipapi server
  become: yes
  copy:
    src: "/opt/application/mitro/release/{{ release_name }}/{{ release_name }}_app/java/FS/dummy.war"
    dest: /opt/application/iisuser
    owner: iisuser
    group: iisuser
    mode: 0775
    remote_src: yes

