---
- name: deploying new war file on fps server
  become: yes
  copy:
    src: "/opt/application/mitro/release/{{ release_name }}/{{ release_name }}_app/java/FS/dummy.war"
    dest: /opt/application/flip
    owner: flip
    group: flip
    mode: 0775
    remote_src: yes

