---
- name: getting package of release {{ release_name }}
  become: yes
  get_url:
    url: "{{ clrapp_sources }}"
    dest: "/opt/application/snipuser/Releases"
    url_username: "{{ sources_user }}"
    url_password: "{{ sources_password }}"
    validate_certs: "no"
    tmp_dest: "/opt/application/snipuser/Releases"
    owner: snipuser
    group: snipuser
    mode: 0775

- name: unzipping package of release {{ release_name }}
  become: yes
  unarchive:
    src: "/opt/application/snipuser/Releases/{{ release_name }}.zip"
    dest: "/opt/application/snipuser/Releases/{{ release_name }}"
    owner: snipuser
    group: snipuser
    mode: 0775
    remote_src: yes

- name: change permission for {{ release_name }} release
  become: yes
  file:
    path: "/opt/application/snipuser/Releases/{{ release_name }}"
    mode: 0775
    owner: snipuser
    group: snipuser
    recurse: yes

- name: checking flipapi server deployment presence in release package
  become: yes
  stat:
    path: "/opt/application/iisuser/Releases/{{ release_name }}/{{ release_name }}_app/java/FS/dummy.war"
  register: flipapi_presence

- name: include flipapi_server.yml
  include: flipapi_server.yml
  when: flipapi_presence.stat.exists == True

- name: checking flip server deployment presence in release package
  become: yes
  stat:
    path: "/opt/application/snipuser/Releases/{{ release_name }}/{{ release_name }}_app/java/FS/dummy.war"
  register: flip_presence

- name: include flip_server.yml
  include: flip_server.yml
  when: flip_presence.stat.exists == True

- name: checking fps server deployment presence in release package
  become: yes
  stat:
    path: "/opt/application/flip/Releases/{{ release_name }}/{{ release_name }}_app/java/FS/dummy.war"
  register: fps_presence

- name: include fps_server.yml
  include: fps_server.yml
  when: fps_presence.stat.exists == True
